### ISSUE TITLE
retirement_warn attribute should be calcultated in seconds but not in days

### ISSUE THREAD

**Issue by ITD27M01** [branic/cloudforms#2]
Currently vm and service retirement_warn attribute represents the number of seconds before the retirement [1]. So method described in blogpost is wrong [2]. If you try to use it, users receive an alert 31/14/7 seconds before the machine is removed [3].

[1] http://manageiq.org/docs/reference/fine/doc-Methods_Available_for_Automation/miq/index
[2] https://cloudformsblog.redhat.com/2016/09/20/notify-vm-owner-of-upcoming-retirement/
[3] https://github.com/branic/cloudforms/blob/master/multiple_retirement_emails/vm_retirement_emails.rb#L22

**Comment by ITD27M01** [comment]
I checked the source code and found that retirement_warn attribute represents the days. My apologizes for this panic. I was confused by the fact that during provision this parameter should be set in seconds but in the database it is stored in days.

https://github.com/ManageIQ/manageiq/blob/fine-4/app/models/miq_provision/retirement.rb#L14

I get a message about "future" retirement of virtual machine at the moment of retirement of the machine because there no handling of zero/nil values (retirement_warn=0). For manageiq it means to send a warning at the time of retirement and I get two messages. The first is that the machine "will be" retired now. The second is that the machine is "already" retired now.

**Comment by branic** [comment]
@ITD27M01 I'd expect that the `vm_retire_warn` event wouldn't be raised if `vm.retirement_warn` is 0 or nil. The method is basically the OOTB method with the `update_retirement_warning` method definition and usage.
